### PR TITLE
[WEB-6754] Some GTM and Google Analytics scripts are blocked by CSP

### PR DESCRIPTION
**Pull request by luke-wyeth**

### CODE REVIEW

**Review by harrietrc — APPROVED** [review]
Looks good to me. Analytics and GTM seem to use a lot more URLs than just the two we were allowing, so I think this is a good fix.

**Comment by jordan-chen-serato** [comment]
Is there a specific reason we're adding this to the base CSP instead of just the id service CSP?

**Comment by luke-wyeth** [comment]
> Is there a specific reason we're adding this to the base CSP instead of just the id service CSP?

that's what was outlined in the story - maybe @harrietrc can shed some light?

**Comment by harrietrc** [comment]
> Is there a specific reason we're adding this to the base CSP instead of just the id service CSP?

The CSP rules here are for JS etc. that's common across all services/sites. (Serato Websites' GTM container loads these same scripts, but they're already allowed by its lack of CSP rules.)

**Review by jordan-chen-serato — APPROVED** [review]

**Pull request merged**
